apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook-list
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-dev
       url: https://kubernetes.default.svc
       values:
         project: default
     - cluster: engineering-prod
       url: https://aca692fc-5468-4d29-b5c5-3d3a8459c533.k8s.ondigitalocean.com
       values:
         project: default
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/YTGhost/argocd-test.git
       targetRevision: HEAD
       path: manifests/guestbook/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: guestbook-ns
     syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true  